name: MobBattle
version: '${project.version}'
main: me.mxtery.mobbattle.MobBattle
api-version: 1.17
commands:
  mobbattle:
    usage: /mb give/help
    description: Main command for the MobBattle plugin. Use /mb help for more info.
    permission: mobbattle.commands
    aliases: [mb]
permissions:
  mobbattle.item:
    description: Allows player to obtain mob battle items via commands
    default: op

